name = "telemetry"
version = "0.1.0"
defaultTargets = ["Telemetry", "TelemetrySdk"]
testDriver = "test"

[leanOptions]
warningAsError = true

[[require]]
name = "plausible"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "Telemetry"

[[lean_lib]]
name = "TelemetrySdk"
roots = ["Telemetry.Sdk"]

[[lean_lib]]
name = "TelemetryTest"

[[lean_exe]]
name = "test"
root = "TelemetryTest"
